services:
  web:
    build: ./src/
    container_name: TecnologieWeb_progetto-web
    volumes:
      - ./src/:/var/www/html
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    env_file:
      - .env
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: TecnologieWeb_progetto-phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    ports:
      - "${DBMS_PORT}:80"
    depends_on:
      - db

  db:
    build: ./db/
    container_name: TecnologieWeb_progetto-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  db_data: